language:generic
sudo: required
services:
 - docker

before_install:
 - docker build -t mklie/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true mklie/docker-react npm run test -- --coverage
